### PR TITLE
Fix save-notebook menu items

### LINKED ISSUE #845: Cannot save notebooks (File -> Save has no effect)
I'm using the current Master (build from spark-notebook.io , 0.8.0-SNAPSHOT-8d5304ca501e856fbda07b0a26a0cdc8b67b47a3 ) and having problems saving my notebook while using the default filesystem storage provider (as given in application.conf)

- File -> Save does NOT save the notebook on the filesystem
- File -> Save (with commit message) -> empty message -> does NOT save the notebook on the filesystem
- File -> Save (with commit message) -> non-empty message -> does save the notebook on the filesystem

EDIT:

CTRL + S also work fine

### PR DESCRIPTION
**Pull request by vidma**
- Bind file->save menu	fixes #845 
- Avoid confusion by incorrect `(autosaved)` message showed even after manual save -> change to `(saved)`
- Show version-control menu items only when supported

### CODE REVIEW

File: app/views/notebook.scala.html [hunk 1]
```diff
@@ -72,17 +72,19 @@
...
-                            <li><a href="#"></a></li>
-                            <li><a href="#"></a></li>
-                            <li><a href="#"></a></li>
-                            <li><a href="#"></a></li>
-                            <li><a href="#"></a></li>
-                          </ul>
-                        </li>
+                        <li id="save_notebook"><a href="#">Save</a></li>
+                        @if(_root_.utils.AppUtils.isVersioningSupported){
+                          <li id="save_checkpoint"><a href="#">Save (with commit message)</a></li>
```
Comment (vidma) [inline app/views/notebook.scala.html]: just added indent
